### ISSUE TITLE
minimum increment for bids?

### ISSUE THREAD

**Issue by tetratorus** [Fluorescent-Linguine/TickrTaker#62]
what should the default minimum increment be? currently it's $1, but maybe we should allow users to set that when posting the item

**Comment by tetratorus** [comment]
also, validation for minimum increment shouldn't be on the client side, because the user can just bypass it

**Comment by k-rathi** [comment]
Ok I will rewrite some of the item backend to also maintain a step size and then also do a validation check on post item
